# Generated by Django 3.1 on 2020-08-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Производитель')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('transmission', models.PositiveSmallIntegerField(choices=[[0, 'manual'], [1, 'automatic'], [2, 'robotic']], verbose_name='Трансмиссия')),
            ],
        ),
    ]
